

INSERT INTO `boisson` (`id_Boisson`, `libelle_Boisson`, `categorie`, `sous_categorie`, `prix`, `logo`) VALUES
(1,'Nikka', 'aperitif', NULL, 7.5, ''),
(2,'1 Litre', 'vin', 'patron', 14, 'pichet.jpg'),
(3,'1/2', 'vin', 'patron', 7.5, 'pichet.jpg'),
(4,'1/4', 'vin', 'patron', 4, 'pichet.jpg'),
(5,'Amaretto', 'digestif', NULL, 4, 'amaretto.jpg'),
(6, 'Amaretto coca', 'aperitif', NULL, 4, 'amaretto.jpg'),
(7, 'Amaretto orange', 'aperitif', NULL, 4, 'amaretto.jpg'),
(8, 'Bacardi coca', 'aperitif', NULL, 3.8, 'bacardi.jpg'),
(9, 'Bardolino', 'vin', 'rose', 15.9, 'bardolino.jpg'),
(10,'Barolo', 'vin', 'rouge', 36, 'barolo.jpg'),
(11,'Café long', 'chaude', NULL, 2, 'cafe.png'),
(12,'Calvados', 'digestif', NULL, 5.5, 'calvados.jpg'),
(13,'Cappuccino', 'chaude', NULL, 2.6, 'Cappuccino.jpg'),
(14,'Chianti', 'vin', 'rouge', 16.8, 'chianti.jpg'),
(15,'Coca cola', 'soft', NULL, 2.6, 'coca.png'),
(16, 'Coca cola light', 'soft', NULL, 2.6, 'coca-light.png'),
(17, 'Coca cola zéro', 'soft', NULL, 2.6, 'coca_zero.png'),
(18, 'Cognac', 'digestif', NULL, 5, 'cognac.jpg'),
(19, 'Desperados', 'biere', 'bouteille', 3.2, 'Desperados.jpg'),
(20, 'Expresso à l''italienne', 'chaude', NULL, 1.9, 'express.png'),
(21, 'Fanta', 'soft', NULL, 2.2, 'fanta.jpg'),
(22, 'Get 27', 'digestif', NULL, 3.5, 'get27.jpg'),
(23, 'Get27', 'aperitif', NULL, 3.5, 'get27.jpg'),
(24, 'Grappa', 'digestif', NULL, 4, 'grappa.jpg'),
(25, 'Heineken', 'biere', 'bouteille', 3, 'heineken.jpg'),
(26, 'Ice tea', 'soft', NULL, 2.2, 'ice-tea.jpg'),
(27, 'Jack Daniels', 'aperitif', NULL, 7, 'jack-daniels.jpg'),
(28, 'JB', 'aperitif', NULL, 4.5, 'jb.jpg'),
(29, 'Kin vin blanc', 'aperitif', NULL, 3, 'kir_vin_vlanc.jpg'),
(30, 'Kir pétillant', 'aperitif', NULL, 4, 'Kir_petillant.jpg'),
(31, 'Kriek', 'biere', 'boueille', 2.8, 'kriek.jpg'),
(32, 'La verre', 'vin', 'patron', 2.2, 'verre.jpg'),
(33, 'Lambrusco', 'vin', 'rouge', 10.9, 'lambrusco.jpg'),
(34, 'Lambrusco rose', 'vin', 'rose', 10.9, 'lambrusco_rose.jpg'),
(35, 'Leffe 15cl', 'biere', 'pression', 1.8, 'leff_pression.jpg'),
(36, 'Leffe 25cl', 'biere', 'pression', 3.2, 'leff_pression.jpg'),
(37, 'Leffe 33cl', 'biere', 'pression', 4, 'leff_pression.jpg'),
(38, 'Leffe 50cl', 'biere', 'pression', 5.9, 'leff_pression.jpg'),
(39, 'Les Hauts de Goelane', 'vin', 'petiteBouteille', 5.9, 'chateau-les-hauts-de-goelane.jpg'),
(40, 'Limoncello', 'digestif', NULL, 4, 'limoncello.jpg'),
(41, 'Marsala', 'digestif', NULL, 3, 'marsala.jpg'),
(42, 'Marsala 8cl ', 'aperitif', NULL, 3, 'marsala.jpg'),
(43, 'Martini blanc', 'aperitif', NULL, 3, 'martini-blanc.jpg'),
(44, 'Martini rouge', 'aperitif', NULL, 3, 'martini-rouge.jpg'),
(45, 'Minute maid orange', 'soft', NULL, 2.2, 'minute-maid-orange.jpg'),
(46, 'Montepulciano', 'vin', 'rouge', 17.9, 'montepulciano.jpg'),
(47, 'Moretti', 'biere', 'bouteille', 4, 'moretti.jpg'),
(48, 'Nastra azzuro', 'biere', 'bouteille', 4, 'nastra-azzuro.jpg'),
(49, 'Nero d''Avola', 'vin', 'rouge', 15.9, 'nerodavola.jpg'),
(50, 'Oasis tropical', 'soft', NULL, 2.2, 'oasis-tropical.jpg'),
(51, 'Pelforth brune', 'biere', 'bouteille', 2.8, 'pelforth-brune.jpg'),
(52, 'Perrier', 'soft', NULL, 2.2, 'perrier.jpg'),
(53, 'Pinot Grigio', 'vin', 'blanc', 15.8, 'pinot-grigio.jpg'),
(54, 'Porto blanc', 'aperitif', NULL, 3, 'porto_blanc.jpg'),
(55, 'Porto rouge', 'aperitif', NULL, 3, 'porto_rouge.jpg'),
(56, 'Ricard', 'aperitif', NULL, 4, 'ricard.jpg'),
(57, 'Rince cochon', 'biere', 'bouteille', 4.5, 'Rince_Cochon.jpg'),
(58, 'Rochemazet', 'vin', 'petiteBouteille', 4.9, 'roche-mazet.jpg'),
(59, 'Sambuca', 'digestif', NULL, 4, 'sambuca.jpg'),
(60, 'San pellegrino 1L', 'soft', NULL, 5, 'san-pellegrino.jpg'),
(61, 'San pellegrino 50cl', 'soft', NULL, 3, 'san-pellegrino.jpg'),
(62, 'Schweppes', 'soft', NULL, 2.2, 'schweppes-agrumes.jpg'),
(63, 'Sprite', 'soft', NULL, 2.2, 'sprite.jpg'),
(64, 'Thé', 'chaude', NULL, 1.9, 'tea.jpg'),
(65, 'Tripel karmeliet', 'biere', 'bouteille', 4.5, 'tripel-karmeliet.jpg'),
(66, 'Verdicchio', 'vin', 'blanc', 11.9, 'Verdicchio.jpg'),
(67, 'Vittel 1L', 'soft', NULL, 5, 'vittel_50_cl.jpg'),
(68, 'Vittel 50cl', 'soft', NULL, 3, 'vittel_50_cl.jpg'),
(69, 'Vodka', 'aperitif', NULL, 4, 'vodka.jpg');

