INSERT INTO `plat` (`id_plat`, `libelle_Plat`, `categorie`, `sous_categorie`, `prix`, `photo`) VALUES
(1, 'Marguerita', 'pizza', 'grande', 7, 'default.png'),
(2, 'Bruschetta alla parmigiana', 'entree', 'chaude', 5.9, 'default.png'),
(3, 'Scampis à l''ail', 'entree', 'chaude', 8.9, 'default.png'),
(4, 'Scampis crème tomate gratinés a la mozzarella', 'entree', 'chaude', 9.8, 'default.png'),
(5, 'Dame blanche', 'dessert', NULL, 4, 'dame-blanche.jpg'),
(6, 'Dame noire', 'dessert', NULL, 4, 'default.png'),
(7, 'Coupe colonel', 'dessert', NULL, 5.5, 'colonel.jpg'),
(8, 'Sorbet mixte', 'dessert', NULL, 5, 'sorbet.jpg'),
(9, 'Coupe junior', 'dessert', NULL, 3, 'coupe-junior.jpg'),
(10, 'Café gourmand', 'dessert', NULL, 6.5, 'cafe-gourmand.png'),
(11, 'Fondant au chocolat', 'dessert', NULL, 5.5, 'fondant-chocolat.jpg'),
(12, 'Pizza nutellissima', 'dessert', NULL, 6, 'pizza-nutella.png'),
(13, 'Pâtes Bolognaise', 'pates', NULL, 8.5, 'default.png'),
(14, 'Pâtes 4 Fromages', 'pates', NULL, 9.5, 'default.png'),
(15, 'Pâtes Maroilles', 'pates', NULL, 9, 'default.png'),
(16, 'Pâtes Saumon', 'pates', NULL, 9.5, 'default.png'),
(18, 'Marguerita', 'pizza', 'petite', 5.9, 'default.png'),
(19, 'Bolognaise', 'pizza', 'petite', 6, 'default.png'),
(20, 'Bolognaise', 'pizza', 'grande', 8, 'default.png'),
(21, 'Jambon', 'pizza', 'petite', 6, 'default.png'),
(22, 'Jambon', 'pizza', 'grande', 8, 'default.png'),
(23, 'Pinnochio', 'pizza', 'petite', 6.2, 'default.png'),
(24, 'Pinnochio', 'pizza', 'grande', 8.2, 'default.png'),
(25, 'Hawaïenne', 'pizza', 'petite', 6.5, 'default.png'),
(26, 'Hawaïenne', 'pizza', 'grande', 8.5, 'default.png'),
(27, 'Capricciosa', 'pizza', 'petite', 6.5, 'default.png'),
(28, 'Capricciosa', 'pizza', 'grande', 8.5, 'default.png'),
(29, 'Napolitine', 'pizza', 'petite', 6.5, 'default.png'),
(30, 'Napolitine', 'pizza', 'grande', 8.5, 'default.png'),
(31, 'Parmigiana', 'pizza', 'petite', 7, 'default.png'),
(32, 'Parmigiana', 'pizza', 'grande', 9, 'default.png'),
(33, '4 Saisons', 'pizza', 'petite', 7, 'default.png'),
(34, '4 Saisons', 'pizza', 'grande', 9, 'default.png'),
(35, 'Cacciatore', 'pizza', 'petite', 7, 'default.png'),
(36, 'Cacciatore', 'pizza', 'grande', 9, 'default.png'),
(37, 'Calzone', 'pizza', 'grande', 9, 'default.png'),
(38, 'Sicilienne', 'pizza', 'petite', 7, 'default.png'),
(39, 'Sicilienne', 'pizza', 'grande', 9, 'default.png'),
(40, 'Kebab', 'pizza', 'petite', 7, 'default.png'),
(41, 'Kebab', 'pizza', 'grande', 9, 'default.png'),
(42, '4 Fromages', 'pizza', 'petite', 7.5, 'default.png'),
(43, '4 Fromages', 'pizza', 'grande', 9.5, 'default.png'),
(44, 'Diavoli', 'pizza', 'petite', 7.5, 'default.png'),
(45, 'Diavoli', 'pizza', 'grande', 9.5, 'default.png'),
(46, 'Etna', 'pizza', 'petite', 7.5, 'default.png'),
(47, 'Etna', 'pizza', 'grande', 9.5, 'default.png'),
(48, 'Arrabiata', 'pizza', 'petite', 8, 'default.png'),
(49, 'Arrabiata', 'pizza', 'grande', 10, 'default.png'),
(50, 'Pescatore', 'pizza', 'petite', 8, 'default.png'),
(51, 'Pescatore', 'pizza', 'grande', 10, 'default.png'),
(52, 'Mamma mia', 'pizza', 'petite', 8.5, 'default.png'),
(53, 'Mamma mia', 'pizza', 'grande', 10, 'default.png'),
(54, 'Savoyarde', 'pizza', 'petite', 8, 'default.png'),
(55, 'Savoyarde', 'pizza', 'grande', 10, 'default.png'),
(56, 'Ch''ti bella', 'pizza', 'petite', 8.5, 'default.png'),
(57, 'Ch''ti bella', 'pizza', 'grande', 10.9, 'default.png'),
(58, 'Capreta', 'pizza', 'petite', 8.5, 'default.png'),
(59, 'Capreta', 'pizza', 'grande', 10.9, 'default.png'),
(60, 'Orientale', 'pizza', 'petite', 8.5, 'default.png'),
(61, 'Orientale', 'pizza', 'grande', 10.9, 'default.png'),
(62, 'Chef', 'pizza', 'petite', 8.5, 'default.png'),
(63, 'Chef', 'pizza', 'grande', 11, 'default.png'),
(64, 'Cipolata', 'pizza', 'petite', 8.5, 'default.png'),
(65, 'Cipolata', 'pizza', 'grande', 11, 'default.png'),
(66, 'Vulcano', 'pizza', 'petite', 8.5, 'default.png'),
(67, 'Vulcano', 'pizza', 'grande', 11.3, 'default.png'),
(68, 'Norvegienne', 'pizza', 'petite', 8.9, 'default.png'),
(69, 'Norvegienne', 'pizza', 'grande', 11.5, 'default.png'),
(70, 'Jambon de parme', 'pizza', 'petite', 8.9, 'default.png'),
(71, 'Jambon de parme', 'pizza', 'grande', 11.8, 'default.png'),
(72, 'Scampis', 'pizza', 'petite', 9, 'default.png'),
(73, 'Scampis', 'pizza', 'grande', 12.5, 'default.png'),
(74, 'Di Salvo', 'pizza', 'petite', 9.2, 'default.png'),
(75, 'Di Salvo', 'pizza', 'grande', 12.8, 'default.png'),
(76, 'Dégustation italienne', 'entree', 'froide', 9.8, 'default.png');